document:
  name: Piano nazionale innovazione 2025
  description: |
    Strategia per l’innovazione tecnologica e la digitalizzazione del Paese 2025
  tags:
    - transizione digitale
    - servizi
    - progetti
    - investimenti
    - innovazione
